version: '3.1'
services:
  mongo:
    image: mongo:5.0.3
    ports:
      - 27017:27017
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongo
  library:
    image: library:latest
    ports:
      - 8080:8080
    environment:
      - MONGODB_HOSTNAME=mongo
    depends_on:
      - mongo